# Dependencies
highlighter:      rouge

# Permalinks
#permalink:        pretty
permalink: /posts/:title

# Setup
title :           Dark Side
tagline:          'cat /dev/brain'
description:      'Dark Side'
url:              http://idarkside.org
baseurl:          '/'
paginate:         5

excerpt_separator:  '<!-- more -->'

author :
  name : Zeratul Ke
  email : zer4tul@gmail.com
  github : zer4tul
  twitter : zer4tul

# plugins
gems:
  - jekyll-sitemap

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zer4tul
production_url : http://www.0x08.org
disqus_shortname: the-dark-side
